### PR TITLE
add life to bodies, completed but untested

### PR DESCRIPTION
**Pull request by okwme**
Having trouble running tests because tone.js imports mp3 and mocha doesn't know what to do there. Checking out a solution with mocking mp3 files in mocha, but might be worth thinking about separating sound dependencies?

### CODE REVIEW

**Comment by okwme** [comment]
hmm mock only works within tests and Anybody is imported before tests start as part of utils...

any ideas how to get tests to run again @psugihara ?

tests that don't run anymore are following:

```
yarn test test/problems.test.js
yarn test test/bodies.test.js
yarn test test/solver.test.js
yarn test test/metadata.test.js
```

**Comment by okwme** [comment]
maybe proxyquire instead?

**Comment by psugihara** [comment]
taking a look

**Comment by psugihara** [comment]
@okwme what node version are you running. think i need to downgrade to get tests running

**Comment by okwme** [comment]
There's a warning from hardhat but it can mostly be ignored. Mentioned it in #40.

I switch between 16 and 18 mostly i think. But that shouldn't make a difference wrt the issue at hand right?

I think import for mp3 only works in context of webpack right? Tests import anybody without transpiling (but then again so does the app itself 🤔

It's crazy to me that js has such different properties depending on the context it's used in 🤪

**Comment by psugihara** [comment]
on 16.20.2 i'm seeing this...

Screenshot 2024-03-16 at 10 58 16 AM

**Comment by psugihara** [comment]
> There's a warning from hardhat but it can mostly be ignored. Mentioned it in https://github.com/okwme/anybody-problem/issues/40.

Ah yeah didn't notice it was just a warning, I get the same config error in with nodejs 20

**Comment by psugihara** [comment]
commented out the `formatest` config key it complains about and get 
`Error HH404: File ./Nft_3_20Verifier.sol, imported from contracts/Solver.sol, not found.`

Maybe I'm missing some local solidity shit you have installed. 🤔

**Comment by psugihara** [comment]
ah no maybe that's because it needs to pull that from network.formatest

**Comment by psugihara** [comment]
ah, think it's bc i didn't have `process.env.deploymentKey`!

@okwme send me your .env when you get a chance

**Comment by psugihara** [comment]
Added `deploymentKey` and `etherscanApiNew` but still getting the same

```
➜  anybody-problem git:(okwme/47-add-life-to-bodies) ✗ yarn sol-test --show-stack-traces                    
yarn run v1.22.17
$ hardhat test test/problems.test.js test/bodies.test.js test/solver.test.js --show-stack-traces
WARNING: You are using a version of Node.js that is not supported, and it may work incorrectly, or not work at all. See https://hardhat.org/nodejs-versions


Error HH404: File ./Nft_3_20Verifier.sol, imported from contracts/Solver.sol, not found.

HardhatError: HH404: File ./Nft_3_20Verifier.sol, imported from contracts/Solver.sol, not found.
    at Resolver.resolveImport (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/internal/solidity/resolver.ts:201:17)
    at /Users/petersugihara/anybody-problem/node_modules/hardhat/src/internal/solidity/dependencyGraph.ts:176:28
    at async Promise.all (index 0)
    at DependencyGraph._addDependenciesFrom (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/internal/solidity/dependencyGraph.ts:174:5)
    at async Promise.all (index 3)
    at Function.createFromResolvedFiles (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/internal/solidity/dependencyGraph.ts:13:5)
    at SimpleTaskDefinition.action (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/builtin-tasks/compile.ts:204:31)
    at Environment._runTaskDefinition (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/internal/core/runtime-environment.ts:330:14)
    at Environment.run (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/internal/core/runtime-environment.ts:163:14)
    at SimpleTaskDefinition.action (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/builtin-tasks/compile.ts:1317:58)

    Caused by: HardhatError: HH400: File contracts/Nft_3_20Verifier.sol doesn't exist.
        at Resolver._validateSourceNameExistenceAndCasing (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/internal/solidity/resolver.ts:476:15)
        at Resolver._resolveLocalSourceName (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/internal/solidity/resolver.ts:252:5)
        at Resolver.resolveImport (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/internal/solidity/resolver.ts:172:24)
        at /Users/petersugihara/anybody-problem/node_modules/hardhat/src/internal/solidity/dependencyGraph.ts:176:28
        at async Promise.all (index 0)
        at DependencyGraph._addDependenciesFrom (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/internal/solidity/dependencyGraph.ts:174:5)
        at async Promise.all (index 3)
        at Function.createFromResolvedFiles (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/internal/solidity/dependencyGraph.ts:13:5)
        at SimpleTaskDefinition.action (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/builtin-tasks/compile.ts:204:31)
        at Environment._runTaskDefinition (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/internal/core/runtime-environment.ts:330:14)
    
        Caused by: HardhatError: HH1005: Solidity source file contracts/Nft_3_20Verifier.sol not found
            at getSourceNameTrueCase (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/utils/source-names.ts:219:13)
            at validateSourceNameExistenceAndCasing (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/utils/source-names.ts:102:30)
            at Resolver._validateSourceNameExistenceAndCasing (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/internal/solidity/resolver.ts:468:7)
            at Resolver._resolveLocalSourceName (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/internal/solidity/resolver.ts:252:5)
            at Resolver.resolveImport (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/internal/solidity/resolver.ts:172:24)
            at /Users/petersugihara/anybody-problem/node_modules/hardhat/src/internal/solidity/dependencyGraph.ts:176:28
            at async Promise.all (index 0)
            at DependencyGraph._addDependenciesFrom (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/internal/solidity/dependencyGraph.ts:174:5)
            at async Promise.all (index 3)
            at Function.createFromResolvedFiles (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/internal/solidity/dependencyGraph.ts:13:5)
        
            Caused by: FileNotFoundError: File /Users/petersugihara/anybody-problem/contracts/Nft_3_20Verifier.sol not found
                at getFileTrueCase (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/internal/util/fs-utils.ts:152:9)
                at getFileTrueCase (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/internal/util/fs-utils.ts:143:9)
                at getSourceNameTrueCase (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/utils/source-names.ts:215:22)
                at validateSourceNameExistenceAndCasing (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/utils/source-names.ts:102:30)
                at Resolver._validateSourceNameExistenceAndCasing (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/internal/solidity/resolver.ts:468:7)
                at Resolver._resolveLocalSourceName (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/internal/solidity/resolver.ts:252:5)
                at Resolver.resolveImport (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/internal/solidity/resolver.ts:172:24)
                at /Users/petersugihara/anybody-problem/node_modules/hardhat/src/internal/solidity/dependencyGraph.ts:176:28
                at async Promise.all (index 0)
                at DependencyGraph._addDependenciesFrom (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/internal/solidity/dependencyGraph.ts:174:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by psugihara** [comment]
o, thinking I need `yarn circom:dev` to run and create those. aye

```
➜  anybody-problem git:(okwme/47-add-life-to-bodies) ✗ yarn circom:dev --show-stack-traces
yarn run v1.22.17
$ hardhat circom --deterministic --debug --verbose --show-stack-traces
  hardhat:core:config Loading Hardhat config from /Users/petersugihara/anybody-problem/hardhat.config.cjs +0ms
  hardhat:core:global-dir Looking up Client Id at /Users/petersugihara/Library/Application Support/hardhat-nodejs/analytics.json +0ms
  hardhat:core:global-dir Client Id found: 1d7f7b33-addd-4364-be7c-00b66c5ae498 +1ms
  hardhat:core:hre Creating HardhatRuntimeEnvironment +0ms
  hardhat:core:hre Running task circom +9ms
  hardhat-circom:info Using cached Powers of Tau file at /Users/petersugihara/anybody-problem/artifacts/circom/hermez.s3-eu-west-1.amazonaws.com_powersOfTau28_hez_final_20.ptau +0ms
  hardhat-circom:info template instances: 6 +732ms
  hardhat-circom:info non-linear constraints: 257 +5ms
  hardhat-circom:info linear constraints: 0 +0ms
  hardhat-circom:info public inputs: 2 +0ms
  hardhat-circom:info public outputs: 1 +0ms
  hardhat-circom:info private inputs: 0 +0ms
  hardhat-circom:info private outputs: 0 +1ms
  hardhat-circom:info wires: 259 +0ms
  hardhat-circom:info labels: 283 +0ms
  hardhat-circom:info Written successfully: /Users/petersugihara/anybody-problem/circuits/absoluteValueSubtraction.r1cs +0ms
  hardhat-circom:info Written successfully: /Users/petersugihara/anybody-problem/circuits/absoluteValueSubtraction.sym +0ms
  hardhat-circom:info Written successfully: /Users/petersugihara/anybody-problem/circuits/absoluteValueSubtraction_js/absoluteValueSubtraction.wat +3ms
Error in plugin hardhat-circom: Unable to compile circuit named: absoluteValueSubtraction

HardhatPluginError: Unable to compile circuit named: absoluteValueSubtraction
    at SimpleTaskDefinition.circomCompile [as action] (/Users/petersugihara/anybody-problem/node_modules/hardhat-circom/dist/index.js:478:19)
    at Environment._runTaskDefinition (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/internal/core/runtime-environment.ts:330:14)
    at Environment.run (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/internal/core/runtime-environment.ts:163:14)
    at main (/Users/petersugihara/anybody-problem/node_modules/hardhat/src/internal/cli/cli.ts:277:7)

    Caused by: RuntimeError: unreachable
        at __rust_start_panic (wasm://wasm/0260c7ce:1:4524617)
        at rust_panic (wasm://wasm/0260c7ce:1:4521276)
        at _ZN3std9panicking20rust_panic_with_hook17hc5c73bd02fe928d4E (wasm://wasm/0260c7ce:1:4521227)
        at _ZN3std9panicking19begin_panic_handler28_$u7b$$u7b$closure$u7d$$u7d$17hcd8b0196239bb506E (wasm://wasm/0260c7ce:1:4517855)
        at _ZN3std10sys_common9backtrace26__rust_end_short_backtrace17h634ecf1fa70ae144E (wasm://wasm/0260c7ce:1:4517644)
        at rust_begin_unwind (wasm://wasm/0260c7ce:1:4519334)
        at _ZN4core9panicking9panic_fmt17h1024bc10a158814eE (wasm://wasm/0260c7ce:1:4551558)
        at _ZN4core6result13unwrap_failed17h4f10a8b6d25baa65E (wasm://wasm/0260c7ce:1:4591194)
        at _ZN6circom16compilation_user11wat_to_wasm17h0ddccdd0eb242234E (wasm://wasm/0260c7ce:1:63934)
        at _ZN6circom16compilation_user7compile17h8ec920719898ded6E (wasm://wasm/0260c7ce:1:59050)
```

**Comment by okwme** [comment]
Ah true hardhat breaks if you dont have a valid mnemonic phrase in your env. Any will suffice for tests. The circom stuff should only matter for the tests outside of contracts that i listed before


Try `yarn test tests/problems.test.js` for ref

**Comment by psugihara** [comment]
cool I will try that

**Comment by okwme** [comment]
any luck?
think i'll just try removing sound to check tests for now

**Comment by psugihara** [comment]
sounds good. didn't have time yesterday but trying now w #50

**Comment by psugihara** [comment]
> Ah true hardhat breaks if you dont have a valid mnemonic phrase in your env. Any will suffice for tests. The circom stuff should only matter for the tests outside of contracts that i listed before
> 
> Try `yarn test tests/problems.test.js` for ref

with this I'm getting the same errors with missing contracts (`Error HH404: File ./Nft_4_20Verifier.sol, imported from contracts/Solver.sol, not found.`)

I tried with `yarn mocha tests/problems.test.js` runs and fails in the way I'm guessing you see (crashing on .mp3 imports) but I do notice it's using an older mocha version than hardhat uses (`yarn mocha --version` is 8.4.0).

In the past when I've used webpack (been a minute) we run the tests through webpack before running them with something like this https://www.npmjs.com/package/mocha-loader

I'll try that next but I'm not sure how/if that'll break the actual contract tests.

**Pull request merged**
