### PR TITLE
70 UI sounds

### PR DESCRIPTION
**Pull request by psugihara**
- got some 1 shot ui sound FX going
- turn down volume on track 4 for balance
- fixed system-wide volume bug that would randomly make it really loud

sounds not final yet, but a good improvement and def more GAME FEEL

### CODE REVIEW

**Comment by okwme** [comment]
Is this R4R @psugihara ? If not I'd suggest using "Draft" until it is and I'll test it out.

**Comment by psugihara** [comment]
yes, r4r

**Comment by okwme** [comment]
Nice! As a first sound I really like the drop 💧👅💧  
It's coming through a bit louder than I'd expect compared to the mix though, might be my headphones but are you experiencing similar levels?

Also great to try out the other tracks while confirming your other points, maybe we should play random track instead of track 1 every time? Would be nice to hear the others more often while developing.

This is also the first time I was able to hear the stereo effects, probably cause I don't use headphones that often but came through finally! Basically it was when a body went off one edge and popped back on the other and the shift was really fast. I like it! My ears aren't as dumb as I thought!


Sound ok tho to:
- [ ] turn down drip shot a little
- [ ] randomize which track

before merging?

**Comment by psugihara** [comment]
cool. thx for playing, will fix! 🦔 👅 🦔

**Pull request merged**
