### PR TITLE
feat: add body hp; they die and whither

### PR DESCRIPTION
**Pull request by psugihara**
working on #44 

So far I wired up the HP and made a little step calculation for incrementing and checking health. They die and whither.

TODO:
- [ ] ugly HP guages
- [ ] All bodies die at the same time. Should they have different HP? Maybe it should correlate to radius?
- [ ] Refine whither animation. Maybe it should pull to the bottom right as they whither like the stars.
Screenshot 2024-03-14 at 2 51 32 PM

Screenshot 2024-03-14 at 2 51 52 PM

### CODE REVIEW

**Comment by okwme** [comment]
nice nice nice

interesting thought re: different starting life / radius... they need to be multiples of 500 as long as 500 is the number of steps in a proof in production (we use 20 step proofs in testing). 

I've got a working version of a single problem play through here:
https://my.machinations.io/d/anybody-problem-v2/713616f4e17011ee900a0ad568087609

if you sign up for machinations i think i can add you to the team if you want to make a copy and try any edits, otherwise i'll try a variation with different starting amounts and see how it changes things.

Having them be the same and stopping play maybe isn't a bad idea anyway tho. like i said we may want to take advantage of opportunities to force the user to submit the proofs and "sync" their universe with the chain.

**Comment by okwme** [comment]
another test:
https://my.machinations.io/d/anybody-problem-v2-wait-to-buy/942ed8c6e2b411ee900a0ad568087609

this is the wait to buy strategy. If the user doesn't buy a new body with the earned tocks as soon as possible they aren't able to generate their 8th body. this is kind of good as it makes the "i don't know what i'm doing" strategy a bad one while still providing a full play through for (as far as i can tell at this point) "optimal" play

**Comment by okwme** [comment]
ok tried some variations of different starting amounts and couldn't find a combination that still allowed the player to get the 10th body without making the other numbers really ugly. Could also just go the route that the lifetime of the bodies is kind of random and the range of random bets better the higher you mint... that would add a lot of nice variability but removes the guarantee of completing heat death with perfect strategy...

**Comment by psugihara** [comment]
>  range of random bets better the higher you mint

do you mean if you mint later you get a better body?

that could be an interesting countervailing mechanic bc with the current ruleset I'd think it's always best to buy new bodies as early as possible.

**Comment by psugihara** [comment]
@okwme rename hp -> life?

**Comment by psugihara** [comment]
changed hp -> life, removed bar

@okwme think we should merge this and I'll get started on the new face logix

**Pull request merged**
