### PR TITLE
full online playthrough completed

### PR DESCRIPTION
**Pull request by okwme**
last tx buying the big boy for 64k: https://sepolia.etherscan.io/tx/0xcd7a9034ca6cfef629aa173361f433024ee119321007b503800082434ae073ad

it took about an hour from the beginning mint tx: https://sepolia.etherscan.io/tx/0x27c2730bcb468c1a12862495f69717b5d42639f451437649660e3365ddd02712

it was also VERY boring.... think there are some UX things that would make it less so but DAMN blockchains are so slow, the thing that took the longest was actually posting the transactions to sepolia all the time.... might be worth reconsidering how to incorporate the missile version 🚀

Also a little worried about possible pricing, when gas costs are above 1 GWEI it costs ~$2 to post. We've seen gas costs down around 0.1 GWEI and lower on Base since the upgrade which would be great at $0.20 cents per tx but still a little worrying that it can go up so fast.

### CODE REVIEW

**Comment by psugihara** [comment]
sick! need to screen revord next time haha

**Comment by okwme** [comment]
here's some late stage baddies for you

https://github.com/okwme/anybody-problem/assets/964052/1c19effe-ada1-4154-bbac-cd9e4fe70979

**Review by psugihara — APPROVED** [review]
lgtm, added a tiny bugfix

**Comment by psugihara** [comment]
> it was also VERY boring.... think there are some UX things that would make it less so but DAMN blockchains are so slow, the thing that took the longest was actually posting the transactions to sepolia all the time.... might be worth reconsidering how to incorporate the missile version 🚀

hm, maybe there are some off-chain components we can add to make the core game loop more fun and varied. I think a key part of UP is that even though the goal is the same (generate $ / tocks), the game and how you think of the game changes significantly a few times even though the mechanic of just clicking buttons to keep accelerating stuff doesn't: make paperclips -> make paperclip makers -> make money other ways.

Don't have a concrete idea but spitballing
- bodies make tocks
- you could have way more bodies per problem and buy them more often (hit more buttons more often)
- bodies could die more often and you constantly buy them
- bodies could get sad and produce less if you don't visit them
- bodies could mate and produce other bodies
- you could make body producers
- could add a narrator in a console telling the story

**Pull request merged**
